Stricter error handling

diff --git a/ppack b/ppack
--- a/ppack
+++ b/ppack
@@ -2,6 +2,11 @@
 
 set -e
 
+function die
+{
+  echo "ppack: error: $@" >&2
+}
+
 # Process arguments.
 dest=$(pwd)
 directories=()
@@ -10,7 +15,7 @@ for arg; do
   case "$arg" in
     --help)
       echo "Usage: packdir [PATHS]..."
-      echo "A small tool for creating directory snapshots."
+      echo "A tool for creating project snapshots."
       echo
       echo "This script will pack the given directories and append a"
       echo "timestamp to the archive name. The timestamp will be either"
@@ -31,22 +36,19 @@ for arg; do
     --dest=*)
       new_dest=${arg#--dest=}
       dest=$(readlink -f "$new_dest" || true)
-      test ! -d "$dest" &&
-        echo "packdir: error: invalid path: \"$new_dest\"" >&2 &&
-        exit 1
+      test ! -d "$dest" && die "invalid path: \"$new_dest\""
       ;;
     -r|--remove-archives)
       remove_archives=yes
       ;;
     *)
+      test -d "$arg" || die "invalid directory: \"$dir\""
       directories+=("$arg")
       ;;
   esac
 done
 
-test ${#directories[@]} == 0 &&
-  echo "packdir: no directories specified" >&2 &&
-  exit
+test ${#directories[@]} == 0 && die "no directories specified"
 
 # Define some color codes.
 blue="$(tput bold)$(tput setf 1)"
@@ -56,49 +58,30 @@ magenta="$(tput bold)$(tput setf 5)"
 yellow="$(tput bold)$(tput setf 6)"
 reset=$(tput sgr0)
 
-# Checks whether the given git repo can be packed and returns 1 otherwise.
-# Must be executed in the parent directory of the project.
+# Returns the timestamp of the latest file in the given directory. If no
+# file could be found, it falls back to the directories timestamp.
 #
-# $1 The project name of the given repository.
-function check_git_repo
+# $1 A valid directory path.
+function find_latest_timestamp
 {
-  ! command -v git >&/dev/null &&
-    echo "${yellow}skipped${reset}: git is not installed: \"$1\"" &&
-    return 1
+  timestamp=$(find "$1" -type f ! -path "*/.git/*" \
+    ! -path "*/.svn/*" ! -path "*/.bzr/*" ! -path "*/.cvs/*" \
+    -exec stat -c "%Y" {} ';' | sort -nr | head -n1)
 
-  ! git -C "$1" show -s HEAD >&/dev/null &&
-    echo "${yellow}skipped${reset}: no commits: \"$1\"" &&
-    return 1
-
-  # Summarize git status.
-  git_status=$(LANG=en git -C "$1" status)
-  case "$git_status" in
-    *Changes\ not\ staged\ for\ commit*)
-      echo "${magenta}unstaged changes${reset}: $1";;
-    *Changes\ to\ be\ committed*)
-      echo "${yellow}uncommitted changes${reset}: $1";;
-    *Your\ branch\ is\ ahead\ of\ \'origin/master\'\ by\ *\ commits*)
-      echo "${green}ready to push${reset}: $1";;
-    *untracked\ files*)
-      echo "${red}untracked files${reset}: $1";;
-  esac
+  test -n "$timestamp" || timestamp=$(stat -c "%Y" "$1")
+  date -d "@$timestamp" +"%d-%m-%y-%H:%M:%S"
 }
 
 for dir in "${directories[@]}"; do
-  test ! -d "$dir/" && \
-    echo "${red}ignore${reset}: invalid directory: \"$dir\"" && \
-    continue
-
-  # Setup environment and try to extract timestamps from git repositories.
   project_path=$(readlink -f "$dir")
   project_name=$(basename "$project_path")
   cd "$(dirname "$project_path")"
   exclude=()
 
   if [[ -d "$project_name/.git" ]]; then
-    check_git_repo "$project_name" || continue
     date_string=$(git -C "$project_name" show -s --format='%ci' HEAD 2>/dev/null |
-      sed -E 's,^..([0-9]{2})-([0-9]{2})-([0-9]{2}) (\S+).*$,\3-\2-\1-\4,g')
+    sed -E 's,^..([0-9]{2})-([0-9]{2})-([0-9]{2}) (\S+).*$,\3-\2-\1-\4,g' ||
+      find_latest_timestamp "$project_name")
 
     # Extract and expand paths in .gitignore.
     test -f "$project_name/.gitignore" &&
@@ -106,15 +89,21 @@ for dir in "${directories[@]}"; do
       do
         exclude+=("$(sed -r 's,^(.*[^/])/*$,--exclude=\1,g' <<< "$file")");
       done
+
+    # Summarize git status.
+    git_status=$(LANG=en git -C "$1" status 2>/dev/null)
+    case "$git_status" in
+      *Changes\ not\ staged\ for\ commit*)
+        echo "${magenta}unstaged changes${reset}: $1";;
+      *Changes\ to\ be\ committed*)
+        echo "${yellow}uncommitted changes${reset}: $1";;
+      *Your\ branch\ is\ ahead\ of\ \'origin/master\'\ by\ *\ commits*)
+        echo "${green}ready to push${reset}: $1";;
+      *untracked\ files*)
+        echo "${red}untracked files${reset}: $1";;
+    esac
   else
-    date_string=$(find "$project_name" -mindepth 1 -exec stat -c "%Y" {} ';' |
-      sort -nr | head -n1)
-
-    test -z "$date_string" &&
-      echo "${yellow}skipped${reset}: empty directory: \"$dir\"" &&
-      continue
-
-    date_string=$(date -d "@$date_string" +"%d-%m-%y-%H:%M:%S")
+    echo
   fi
 
   archive_path="${dest}/${project_name}-${date_string}.tar.xz"
