Implemented --help for print-gentoo-splash

diff --git a/print-gentoo-splash b/print-gentoo-splash
--- a/print-gentoo-splash
+++ b/print-gentoo-splash
@@ -4,13 +4,21 @@
 # avoid additional dependencies and was intended to be used inside the
 # Linux console running a simple shell.
 
+# Prints the given error messages and terminates the program with an error
+# message.
+die()
+{
+  echo "error: $@" >&2
+  exit 1
+}
+
 # Asserts that the given color code is valid.
 #
 # $1 A color like "0;30", code without any escape sequences.
 assert_color()
 {
   echo -n "$1" | grep -E '^(0|[01];[34][0-9])$' >&/dev/null ||
-    { echo "error: invalid color: \"$1\"" && exit 1; }
+    die "invalid color: $1"
 }
 
 # This function repeats a string and takes two arguments:
@@ -23,6 +31,28 @@ repeat_string()
 }
 
 # Process arguments.
+test $# -lt 4 || die "too many arguments"
+for arg; do
+  if [[ "$arg" == "--help" ]]; then
+    echo "Usage: print-gentoo-splash [COLORS]"
+    echo "Prints a colorized Gentoo logo."
+    echo
+    echo "This script takes up to 3 color codes like e.g. \"1;34\","
+    echo "specifying a dark, a medium and a bright shade. The first"
+    echo "argument may also specify one of the colors listed below, in"
+    echo "which case the last two arguments will be ignored."
+    echo "  * red"
+    echo "  * green"
+    echo "  * yellow"
+    echo "  * blue"
+    echo "  * cyan"
+    echo "  * white"
+    echo "  * grey"
+    echo "  * magenta (default)"
+    exit
+  fi
+done
+
 case "$1" in
   red)     dark="0;31" medium="1;31" bright="1;37";;
   green)   dark="0;32" medium="1;32" bright="1;37";;
